axon:
  axonserver:
    servers: localhost:8124
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost/cqrs
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database: postgresql